# Generated by Django 4.2.3 on 2023-08-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchase_user'),
        ('user', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
