version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
      - celery-beat

  redis:
    image: redis:latest

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A myproject worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A myproject beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
